# -*- coding: utf-8 -*-
"""finetuning_fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvFzxsgxmgCvoDlNlbjZ0JQmJH_6SwV_

## WITH FINE-TUNING — BERT, RoBERTa, DistilBERT
Training  : fewshot_examples.csv       (40 labeled samples)
Evaluation: test_data_with_labels.csv  (289 samples)

Outputs:
  - results_without_finetuning.json    (ZS, ZS-CoT, FS, FS-CoT metrics)
  - results_finetuned.json             (fine-tuned metrics)
  - summary_all.csv                    (full comparison table)
  - saved_models/<MODEL>/              (saved fine-tuned weights)
"""

from google.colab import drive
drive.mount('/content/drive')

import os

colab_notebooks_path = '/content/drive/MyDrive/Colab Notebooks/bert/data'

if os.path.exists(colab_notebooks_path):
    print(f"Contents of '{colab_notebooks_path}':")
    for item in os.listdir(colab_notebooks_path):
        print(item)
else:
    print(f"The folder '{colab_notebooks_path}' does not exist. Please ensure 'Colab Notebooks' is directly in your Google Drive's 'MyDrive'.")

import os
import json
import warnings
import numpy as np
import pandas as pd
from sklearn.metrics import (accuracy_score, f1_score,
                             precision_score, recall_score,
                             classification_report)
from sklearn.metrics.pairwise import cosine_similarity
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModel,
    AutoModelForSequenceClassification,
    get_linear_schedule_with_warmup,
    pipeline,
)
from torch.optim import AdamW
from tqdm import tqdm

warnings.filterwarnings("ignore")

# torch.device — works for both pipeline (int) and PyTorch .to()
DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DEVICE_INT = 0 if torch.cuda.is_available() else -1   # for HuggingFace pipeline
print(f"Using device: {DEVICE}")

"""## Global variables, models, and fine-tuning parameters"""

# ── Paths
FEWSHOT_PATH  = "/content/drive/MyDrive/Colab Notebooks/bert/data/fewshot_examples.csv"
TEST_PATH     = "/content/drive/MyDrive/Colab Notebooks/bert/data/test_data_with_labels.csv"
RESULTS_FT    = "/content/drive/MyDrive/Colab Notebooks/bert/results_finetuned.json"
RESULTS_NO_FT = "/content/drive/MyDrive/Colab Notebooks/bert/results_without_finetuning.json"
SUMMARY_PATH  = "/content/drive/MyDrive/Colab Notebooks/bert/summary_all.csv"
SAVE_DIR      = "/content/drive/MyDrive/Colab Notebooks/bert/saved_models_finetune"

# ── Column names
TEXT_COLUMN  = 'text'
LABEL_COLUMN = 'Label'

#  Fine-tuning parameters
MAX_LEN      = 256
BATCH_SIZE   = 8
EPOCHS       = 10
LR           = {
    "BERT":       2e-5,
    "RoBERTa":    5e-6,    #1e-5,
    "DistilBERT": 2e-5,
}
WARMUP_RATIO = 0.1
WEIGHT_DECAY = 0.01
NUM_LABELS   = 2

# ── Few-Shot parameter
K_NEIGHBORS  = 5

# ── Model checkpoints
CHECKPOINTS = {
    "BERT":       "bert-base-uncased",
    "RoBERTa":    "roberta-base",
    "DistilBERT": "distilbert-base-uncased",
}

# ── NLI models for Zero-Shot
NLI_MODELS = {
    "BERT":       "cross-encoder/nli-MiniLM2-L6-H768",
    "RoBERTa":    "cross-encoder/nli-roberta-base",
    "DistilBERT": "typeform/distilbert-base-uncased-mnli",
}

"""## Zero-Shot and Zero-Shot CoT prompts"""

# ── Zero-Shot labels
CANDIDATE_LABELS_ZS = [
    "The author is personally experiencing burnout, stress, or a mental health "
    "struggle related to their cybersecurity job or career.",
    "This is a general cybersecurity discussion with no personal burnout "
    "or mental health signals from the author.",
]

# ── Zero-Shot CoT themes (OR logic — any theme fires = Label 1) ──
COT_THEMES = [
    (
        "The author is personally experiencing burnout, exhaustion, or feeling overwhelmed by work demands.",
        "The author does not mention burnout or feeling overwhelmed by work."
    ),
    (
        "The author personally mentions anxiety, depression, PTSD, or mental health struggles tied to their job.",
        "The author does not mention any mental health struggles related to work."
    ),
    (
        "The author personally struggles with work-life balance, sleep issues, or feeling emotionally drained.",
        "The author does not mention work-life balance problems or emotional exhaustion."
    ),
    (
        "The author is personally stressed about job searching, interviews, layoffs, or career uncertainty.",
        "The author is not expressing stress about job searching or career uncertainty."
    ),
    (
        "The author personally describes a toxic workplace, high pressure environment, or ethical stress at work.",
        "The author does not describe a toxic or high-pressure workplace."
    ),
    (
        "The author personally expresses feeling not good enough, imposter syndrome, or struggling with job tasks.",
        "The author does not express self-doubt or imposter syndrome."
    ),
    (
        "The author personally struggles to stay motivated or keep up with demands of the cybersecurity field.",
        "The author does not mention difficulty staying motivated in their field."
    ),
]

THEME_THRESHOLD = 0.5

"""## Load data"""

# ── Load files
few_df  = pd.read_csv(FEWSHOT_PATH)
test_df = pd.read_csv(TEST_PATH)

# ── Extract plain lists — used across all strategies
few_texts  = few_df[TEXT_COLUMN].tolist()
few_labels = few_df[LABEL_COLUMN].tolist()
test_texts = test_df[TEXT_COLUMN].tolist()
y_true     = test_df[LABEL_COLUMN].tolist()

print(f"Few-shot : {len(few_df)} samples  (Label 0: {few_labels.count(0)}, Label 1: {few_labels.count(1)})")
print(f"Test     : {len(test_df)} samples  (Label 0: {y_true.count(0)}, Label 1: {y_true.count(1)})")

"""## Evaluate function (shared by all strategies)"""

# ── strategy param so the label is correct for ZS/FS/FT ──────
def evaluate(y_true, y_pred, model_name, strategy="Fine-tuned"):
    acc  = accuracy_score(y_true, y_pred)
    f1   = f1_score(y_true, y_pred, average="macro")
    prec = precision_score(y_true, y_pred, average="macro", zero_division=0)
    rec  = recall_score(y_true, y_pred, average="macro", zero_division=0)
    print(f"\n  [{model_name} | {strategy}]")
    print(f"    Accuracy  : {acc:.4f}")
    print(f"    F1 (macro): {f1:.4f}")
    print(f"    Precision : {prec:.4f}")
    print(f"    Recall    : {rec:.4f}")
    print(classification_report(y_true, y_pred,
          target_names=["No Signal (0)", "Burnout/Stress (1)"],
          zero_division=0))
    return {"accuracy": acc, "f1_macro": f1, "precision": prec, "recall": rec}

"""## Zero-Shot and Zero-Shot CoT functions"""

# ── Zero-Shot ─────────────────────────────────────────────────
def zero_shot(classifier, texts):
    preds = []
    for text in texts:
        result = classifier(text, candidate_labels=CANDIDATE_LABELS_ZS,
                            multi_label=False)
        pred = 1 if result["labels"][0] == CANDIDATE_LABELS_ZS[0] else 0
        preds.append(pred)
    return preds

# ── Zero-Shot CoT ─────────────────────────────────────────────
def zero_shot_cot(classifier, texts):
    preds = []
    for text in texts:
        fired = False
        for pos_label, neg_label in COT_THEMES:
            result = classifier(text,
                                candidate_labels=[pos_label, neg_label],
                                multi_label=False)
            pos_score = result["scores"][result["labels"].index(pos_label)]
            if pos_score >= THEME_THRESHOLD:
                fired = True
                break
        preds.append(1 if fired else 0)
    return preds

"""## Embedding helpers, Few-Shot and Few-Shot CoT functions"""

# ── Embedding helper (shared by FS & FS-CoT) ─────────────────
def mean_pool(token_embeddings, attention_mask):
    mask = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return (token_embeddings * mask).sum(1) / mask.sum(1).clamp(min=1e-9)

def get_embeddings(texts, tokenizer, model, batch_size=16):
    model.eval()
    all_embs = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i: i + batch_size]
        enc = tokenizer(batch, padding=True, truncation=True,
                        max_length=512, return_tensors="pt")
        enc = {k: v.to(DEVICE) for k, v in enc.items()}
        with torch.no_grad():
            out = model(**enc)
        embs = mean_pool(out.last_hidden_state, enc["attention_mask"])
        all_embs.append(embs.cpu().numpy())
    return np.vstack(all_embs)

# ── Few-Shot
def few_shot(test_texts, few_texts, few_labels, tokenizer, model):
    print("    Encoding few-shot examples ...")
    few_embs  = get_embeddings(few_texts,  tokenizer, model)
    print("    Encoding test samples ...")
    test_embs = get_embeddings(test_texts, tokenizer, model)
    sim_matrix = cosine_similarity(test_embs, few_embs)
    preds = []
    for sims in sim_matrix:
        top_k_idx    = np.argsort(sims)[-K_NEIGHBORS:]
        top_k_labels = [few_labels[i] for i in top_k_idx]
        preds.append(int(np.round(np.mean(top_k_labels))))
    return preds

# ── Few-Shot CoT
def few_shot_cot(test_texts, few_texts, few_labels, tokenizer, model):
    few_reasons   = few_df["label_reason"].tolist()
    few_cot_texts = [
        f"{text} [REASON: {reason}]"
        for text, reason in zip(few_texts, few_reasons)
    ]
    print("    Encoding CoT-enriched few-shot examples ...")
    few_embs  = get_embeddings(few_cot_texts, tokenizer, model)
    print("    Encoding test samples ...")
    test_embs = get_embeddings(test_texts,    tokenizer, model)
    sim_matrix = cosine_similarity(test_embs, few_embs)
    preds = []
    for sims in sim_matrix:
        top_k_idx    = np.argsort(sims)[-K_NEIGHBORS:]
        top_k_labels = [few_labels[i] for i in top_k_idx]
        preds.append(int(np.round(np.mean(top_k_labels))))
    return preds

"""## Run Zero-Shot, Zero-Shot CoT, Few-Shot, Few-Shot CoT"""

no_ft_results = {}

for model_name in ["BERT", "RoBERTa", "DistilBERT"]:
    print(f"\n{'='*60}\n  MODEL: {model_name}\n{'='*60}")
    results = {}

    # ── Zero-Shot & Zero-Shot CoT (NLI) ───────────────────────
    try:
        clf = pipeline("zero-shot-classification",
                       model=NLI_MODELS[model_name], device=DEVICE_INT)

        print("\n  Running Zero-Shot ...")
        preds_zs = zero_shot(clf, test_texts)
        results["ZeroShot"] = evaluate(y_true, preds_zs, model_name, "Zero-Shot")

        print("\n  Running Zero-Shot CoT ...")
        preds_zscot = zero_shot_cot(clf, test_texts)
        results["ZeroShot_CoT"] = evaluate(y_true, preds_zscot, model_name, "Zero-Shot CoT")

        del clf
        torch.cuda.empty_cache()
    except Exception as e:
        print(f"  ⚠ NLI failed: {e}")
        results["ZeroShot"]     = {"error": str(e)}
        results["ZeroShot_CoT"] = {"error": str(e)}

    # ── Few-Shot & Few-Shot CoT (base model embeddings) ───────
    try:
        tokenizer = AutoTokenizer.from_pretrained(CHECKPOINTS[model_name])
        emb_model = AutoModel.from_pretrained(CHECKPOINTS[model_name]).to(DEVICE)

        print("\n  Running Few-Shot ...")
        preds_fs = few_shot(test_texts, few_texts, few_labels, tokenizer, emb_model)
        results["FewShot"] = evaluate(y_true, preds_fs, model_name, "Few-Shot")

        print("\n  Running Few-Shot CoT ...")
        preds_fscot = few_shot_cot(test_texts, few_texts, few_labels, tokenizer, emb_model)
        results["FewShot_CoT"] = evaluate(y_true, preds_fscot, model_name, "Few-Shot CoT")

        del emb_model, tokenizer
        torch.cuda.empty_cache()
    except Exception as e:
        print(f"   Embedding model failed: {e}")
        results["FewShot"]     = {"error": str(e)}
        results["FewShot_CoT"] = {"error": str(e)}

    no_ft_results[model_name] = results

with open(RESULTS_NO_FT, "w") as f:
    json.dump(no_ft_results, f, indent=2)
print(f"\n No-FT results saved → {RESULTS_NO_FT}")

"""## PyTorch Dataset"""

"""
PyTorch Dataset for the binary cybersecurity classification task.
"""
class CyberDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=MAX_LEN):
        self.texts     = texts
        self.labels    = labels
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

"""## Training loop"""

def train_epoch(model, loader, optimizer, scheduler):
    model.train()
    total_loss, n_correct, n_total = 0.0, 0, 0
    for batch in loader:
        batch   = {k: v.to(DEVICE) for k, v in batch.items()}
        outputs = model(**batch)
        loss    = outputs.loss
        preds   = outputs.logits.argmax(dim=-1)

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item() * len(batch["labels"])
        n_correct  += (preds == batch["labels"]).sum().item()
        n_total    += len(batch["labels"])

    return total_loss / n_total, n_correct / n_total

"""## Predict function"""

@torch.no_grad()
def predict(model, loader):
    model.eval()
    all_preds = []
    for batch in loader:
        batch  = {k: v.to(DEVICE) for k, v in batch.items()}
        logits = model(**{k: v for k, v in batch.items()
                          if k != "labels"}).logits
        all_preds.extend(logits.argmax(dim=-1).cpu().tolist())
    return all_preds

"""## Fine-tune and evaluate"""

def finetune_model(model_name):
    print(f"\n{'='*60}")
    print(f"  MODEL: {model_name}")
    print(f"{'='*60}")

    ckpt      = CHECKPOINTS[model_name]
    lr        = LR[model_name]
    save_path = os.path.join(SAVE_DIR, model_name)          #  fixed: was a tuple

    # ── Tokenizer & Model
    print(f"  Loading {ckpt} ...")
    tokenizer = AutoTokenizer.from_pretrained(ckpt)
    model     = AutoModelForSequenceClassification.from_pretrained(
        ckpt, num_labels=NUM_LABELS
    ).to(DEVICE)

    # ── Datasets & Loaders
    train_ds = CyberDataset(few_df[TEXT_COLUMN].tolist(),
                            few_df[LABEL_COLUMN].tolist(), tokenizer)
    test_ds  = CyberDataset(test_df[TEXT_COLUMN].tolist(),
                            test_df[LABEL_COLUMN].tolist(), tokenizer)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    test_loader  = DataLoader(test_ds,  batch_size=32,         shuffle=False)

    # ── Optimizer & Scheduler
    optimizer    = AdamW(model.parameters(), lr=lr, weight_decay=WEIGHT_DECAY)
    total_steps  = len(train_loader) * EPOCHS
    warmup_steps = int(total_steps * WARMUP_RATIO)
    scheduler    = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )

    # ── Training
    print(f"\n  Training for {EPOCHS} epochs ...")
    best_f1, best_state = 0.0, None

    for epoch in tqdm(range(1, EPOCHS + 1), desc=f"  {model_name}"):
        train_loss, train_acc = train_epoch(model, train_loader, optimizer, scheduler)
        preds  = predict(model, test_loader)
        val_f1 = f1_score(test_df[LABEL_COLUMN].tolist(), preds, average="macro")  #  fixed: was hardcoded "Label"
        tqdm.write(f"    Epoch {epoch:2d} | "
                   f"train_loss={train_loss:.4f}  train_acc={train_acc:.4f}  "
                   f"val_f1={val_f1:.4f}")
        if val_f1 > best_f1:
            best_f1    = val_f1
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

    # ── Load best checkpoint
    print(f"\n  Best validation F1: {best_f1:.4f}  →  loading best weights")
    model.load_state_dict({k: v.to(DEVICE) for k, v in best_state.items()})

    # ── Final Evaluation
    final_preds = predict(model, test_loader)
    metrics     = evaluate(test_df[LABEL_COLUMN].tolist(), final_preds, model_name, "Fine-tuned")

    # ── Save Fine-tuned Model
    os.makedirs(save_path, exist_ok=True)                   #  fixed: was commented out
    model.save_pretrained(save_path)
    tokenizer.save_pretrained(save_path)
    print(f"  Model saved → {save_path}/")

    # ── Free memory
    del model, tokenizer
    torch.cuda.empty_cache()

    return metrics

"""## Run fine-tuning"""

print("\n" + "="*60)
print("  PHASE 2 — WITH FINE-TUNING")
print("="*60)

os.makedirs(SAVE_DIR, exist_ok=True)

all_results = {}
for model_name in ["BERT", "RoBERTa", "DistilBERT"]:
    try:
        all_results[model_name] = finetune_model(model_name)  #  fixed: no args
    except Exception as e:
        print(f"  ⚠ {model_name} failed: {e}")
        all_results[model_name] = {"error": str(e)}

with open(RESULTS_FT, "w") as f:                             #  fixed: was RESULTS_PATH
    json.dump(all_results, f, indent=2)
print(f"\n Fine-tuning results saved → {RESULTS_FT}")

"""## Full comparison summary (all strategies + all models)"""

rows = []

# ── No fine-tuning strategies
for model, strategies in no_ft_results.items():              #  fixed: was missing entirely
    for strat, metrics in strategies.items():
        if "accuracy" in metrics:
            rows.append({
                "Model":     model,
                "Strategy":  strat,
                "Accuracy":  round(metrics["accuracy"], 4),
                "F1_Macro":  round(metrics["f1_macro"], 4),
                "Precision": round(metrics["precision"], 4),
                "Recall":    round(metrics["recall"], 4),
            })

# ── Fine-tuned
for model, metrics in all_results.items():
    if "accuracy" in metrics:
        rows.append({
            "Model":     model,
            "Strategy":  "Fine-tuned",
            "Accuracy":  round(metrics["accuracy"], 4),
            "F1_Macro":  round(metrics["f1_macro"], 4),
            "Precision": round(metrics["precision"], 4),
            "Recall":    round(metrics["recall"], 4),
        })

summary = pd.DataFrame(rows)
pd.set_option("display.float_format", "{:.4f}".format)
print(summary.to_string(index=False))
summary.to_csv(SUMMARY_PATH, index=False)                    #  fixed: uses SUMMARY_PATH global
print(f"\n Full summary saved → {SUMMARY_PATH}")