# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORQSoW5ZIwsEGGGcYL6zHfW1LtJnipHC

## INFERENCE ON UNLABELED DATA
Runs the two best models from the experiment phase on `test_data_unlabeled.csv`:
- **RoBERTa FewShot_CoT** (F1=0.7612) — embedding k-NN with label_reason context
- **DistilBERT Fine-tuned** (F1=0.7541) — loads saved fine-tuned weights

Output: `inference_predictions.csv` with a predicted label from each model per post.
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import warnings
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
from sklearn.metrics.pairwise import cosine_similarity

warnings.filterwarnings('ignore')

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {DEVICE}')

"""## Paths and config"""

# ── Input files ───────────────────────────────────────────────
UNLABELED_PATH  = '/content/drive/MyDrive/Colab Notebooks/bert/data/test_data_unlabeled.csv'
FEWSHOT_PATH    = '/content/drive/MyDrive/Colab Notebooks/bert/data/fewshot_examples.csv'

# ── Saved fine-tuned model (DistilBERT) ───────────────────────
DISTILBERT_MODEL_PATH = '/content/drive/MyDrive/Colab Notebooks/bert/saved_models_finetune/DistilBERT'

# ── RoBERTa base checkpoint (for FewShot_CoT embeddings) ─────
ROBERTA_CHECKPOINT = 'roberta-base'

# ── Output ────────────────────────────────────────────────────
OUTPUT_PATH = '/content/drive/MyDrive/Colab Notebooks/bert/inference_predictions.csv'

# ── Column names ──────────────────────────────────────────────
TEXT_COLUMN  = 'text'
LABEL_COLUMN = 'Label'

# ── Few-Shot config ───────────────────────────────────────────
K_NEIGHBORS = 5
MAX_LEN     = 256

"""## Load data"""

# ── Unlabeled posts to predict on ─────────────────────────────
unlabeled_df = pd.read_csv(UNLABELED_PATH)

# ── Few-shot examples (used as reference for RoBERTa k-NN) ───
few_df       = pd.read_csv(FEWSHOT_PATH)

predict_texts = unlabeled_df[TEXT_COLUMN].tolist()
few_texts     = few_df[TEXT_COLUMN].tolist()
few_labels    = few_df[LABEL_COLUMN].tolist()

print(f'Posts to predict : {len(unlabeled_df)}')
print(f'Few-shot examples: {len(few_df)}')

"""## Model 1 — RoBERTa FewShot_CoT (best overall F1=0.7612)"""

# ── Embedding helpers ─────────────────────────────────────────
def mean_pool(token_embeddings, attention_mask):
    mask = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return (token_embeddings * mask).sum(1) / mask.sum(1).clamp(min=1e-9)

def get_embeddings(texts, tokenizer, model, batch_size=16):
    model.eval()
    all_embs = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i: i + batch_size]
        enc = tokenizer(batch, padding=True, truncation=True,
                        max_length=512, return_tensors='pt')
        enc = {k: v.to(DEVICE) for k, v in enc.items()}
        with torch.no_grad():
            out = model(**enc)
        embs = mean_pool(out.last_hidden_state, enc['attention_mask'])
        all_embs.append(embs.cpu().numpy())
    return np.vstack(all_embs)

# ── RoBERTa FewShot_CoT inference ─────────────────────────────
print('Loading RoBERTa base for embedding...')
rb_tokenizer = AutoTokenizer.from_pretrained(ROBERTA_CHECKPOINT)
rb_model     = AutoModel.from_pretrained(ROBERTA_CHECKPOINT).to(DEVICE)

# Enrich few-shot texts with label_reason (same as training)
few_reasons   = few_df['label_reason'].tolist()
few_cot_texts = [
    f'{text} [REASON: {reason}]'
    for text, reason in zip(few_texts, few_reasons)
]

print('Encoding CoT-enriched few-shot examples...')
few_embs     = get_embeddings(few_cot_texts, rb_tokenizer, rb_model)
print('Encoding unlabeled posts...')
predict_embs = get_embeddings(predict_texts, rb_tokenizer, rb_model)

# k-NN majority vote
sim_matrix = cosine_similarity(predict_embs, few_embs)
roberta_preds = []
for sims in sim_matrix:
    top_k_idx    = np.argsort(sims)[-K_NEIGHBORS:]
    top_k_labels = [few_labels[i] for i in top_k_idx]
    roberta_preds.append(int(np.round(np.mean(top_k_labels))))

del rb_model, rb_tokenizer
torch.cuda.empty_cache()

print(f'RoBERTa FewShot_CoT done.')
print(f'  Predicted Label 1 (burnout): {roberta_preds.count(1)}')
print(f'  Predicted Label 0 (no signal): {roberta_preds.count(0)}')

"""## Model 2 — DistilBERT Fine-tuned (F1=0.7541)"""

import os
import warnings
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
from sklearn.metrics.pairwise import cosine_similarity

warnings.filterwarnings('ignore')

# ── Dataset for DataLoader ────────────────────────────────────
class InferenceDataset(Dataset):
    def __init__(self, texts, tokenizer, max_len=MAX_LEN):
        self.texts     = texts
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            max_length=self.max_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt',
        )
        return {k: v.squeeze(0) for k, v in enc.items()}

# ── Load saved DistilBERT fine-tuned weights ──────────────────
print(f'Loading fine-tuned DistilBERT from: {DISTILBERT_MODEL_PATH}')
db_tokenizer = AutoTokenizer.from_pretrained(DISTILBERT_MODEL_PATH, local_files_only=True)
db_model     = AutoModelForSequenceClassification.from_pretrained(
    DISTILBERT_MODEL_PATH, local_files_only=True
).to(DEVICE)

# ── Run inference ─────────────────────────────────────────────
infer_ds     = InferenceDataset(predict_texts, db_tokenizer)
infer_loader = DataLoader(infer_ds, batch_size=32, shuffle=False)

db_model.eval()
distilbert_preds = []

with torch.no_grad():
    for batch in infer_loader:
        batch  = {k: v.to(DEVICE) for k, v in batch.items()}
        logits = db_model(**batch).logits
        distilbert_preds.extend(logits.argmax(dim=-1).cpu().tolist())

del db_model, db_tokenizer
torch.cuda.empty_cache()

print(f'DistilBERT Fine-tuned done.')
print(f'  Predicted Label 1 (burnout): {distilbert_preds.count(1)}')
print(f'  Predicted Label 0 (no signal): {distilbert_preds.count(0)}')

"""## Save predictions"""

# ── Build output DataFrame ────────────────────────────────────
output_df = unlabeled_df[['id', TEXT_COLUMN]].copy()

output_df['pred_RoBERTa_FewShot_CoT']    = roberta_preds
output_df['pred_DistilBERT_Finetuned']   = distilbert_preds

# ── Agreement column — both models agree on prediction ────────
output_df['models_agree'] = (
    output_df['pred_RoBERTa_FewShot_CoT'] ==
    output_df['pred_DistilBERT_Finetuned']
)

# ── Label descriptions for readability ───────────────────────
label_map = {1: 'Burnout/Stress Signal', 0: 'No Signal'}
output_df['pred_RoBERTa_label']    = output_df['pred_RoBERTa_FewShot_CoT'].map(label_map)
output_df['pred_DistilBERT_label'] = output_df['pred_DistilBERT_Finetuned'].map(label_map)

# ── Save ──────────────────────────────────────────────────────
output_df.to_csv(OUTPUT_PATH, index=False)
print(f'\n Predictions saved → {OUTPUT_PATH}')

# ── Summary ───────────────────────────────────────────────────
print(f'\nTotal posts predicted: {len(output_df)}')
print(f'\nRoBERTa FewShot_CoT:')
print(output_df['pred_RoBERTa_label'].value_counts().to_string())
print(f'\nDistilBERT Fine-tuned:')
print(output_df['pred_DistilBERT_label'].value_counts().to_string())
print(f'\nBoth models agree on: {output_df["models_agree"].sum()} / {len(output_df)} posts')
print(f'Disagreement on     : {(~output_df["models_agree"]).sum()} posts')

"""## Preview predictions"""

# ── Show sample predictions ───────────────────────────────────
pd.set_option('display.max_colwidth', 80)

print('=== Posts where BOTH models predict Burnout/Stress ===')
both_burnout = output_df[
    (output_df['pred_RoBERTa_FewShot_CoT'] == 1) &
    (output_df['pred_DistilBERT_Finetuned'] == 1)
]
print(f'Count: {len(both_burnout)}')
print(both_burnout[['id', 'text']].head(3).to_string())

print('\n=== Posts where models DISAGREE ===')
disagree = output_df[~output_df['models_agree']]
print(f'Count: {len(disagree)}')
print(disagree[['id', 'text', 'pred_RoBERTa_label', 'pred_DistilBERT_label']].head(5).to_string())