# -*- coding: utf-8 -*-
"""without_finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15okElnUPBp_Ce4zEB0N2qWEmWZnUu2Ve

*WITHOUT Finetuning- Zero shot and Few SHot Classification*

Model: BERT, ROberta, DistilBERT

1. Zero-Shot (ZS)        — NLI-based classification, no examples
  2. Zero-Shot CoT (ZS-CoT)— Multi-step NLI reasoning chain
  3. Few-Shot (FS)         — Embedding similarity + k-NN from 40 labeled examples
  4. Few-Shot CoT (FS-CoT) — k-NN but using label_reason context in embeddings

outputs: summary_withoutFINETUNE.csv, results_without_finetune.json
"""

from google.colab import drive
drive.mount('/content/drive')

import os

colab_notebooks_path = '/content/drive/MyDrive/Colab Notebooks/bert/data'

if os.path.exists(colab_notebooks_path):
    print(f"Contents of '{colab_notebooks_path}':")
    for item in os.listdir(colab_notebooks_path):
        print(item)
else:
    print(f"The folder '{colab_notebooks_path}' does not exist. Please ensure 'Colab Notebooks' is directly in your Google Drive's 'MyDrive'.")

# libraries
import os
import re
import json
import warnings
import numpy as np
import pandas as pd
from sklearn.metrics import (accuracy_score, f1_score,
                             precision_score, recall_score,
                             classification_report)
from sklearn.metrics.pairwise import cosine_similarity
import torch
from transformers import (
    pipeline,
    AutoTokenizer,
    AutoModel,
)

DEVICE = 0 if torch.cuda.is_available() else -1   # GPU if available
device_str = "cuda" if torch.cuda.is_available() else "cpu"

"""## assign global var and models"""

FEWSHOT_PATH  = "/content/drive/MyDrive/Colab Notebooks/bert/data/fewshot_examples.csv"
TEST_PATH     = "/content/drive/MyDrive/Colab Notebooks/bert/data/test_data_with_labels.csv"
RESULTS_PATH  = "/content/drive/MyDrive/Colab Notebooks/bert/data/results_without_finetuning.json"


MAX_TEXT_LEN  = 400   # characters; keeps inference fast, covers most posts
K_NEIGHBORS   = 5     # k for few-shot k-NN

#NLI Models - better for zero shot classification

NLI_MODELS = {
    "BERT":       "cross-encoder/nli-MiniLM2-L6-H768",
    "RoBERTa":    "cross-encoder/nli-roberta-base",
    "DistilBERT": "typeform/distilbert-base-uncased-mnli",
}


#Base Model checkpoints
BASE_MODELS = {
    "BERT":       "bert-base-uncased",
    "RoBERTa":    "roberta-base",
    "DistilBERT": "distilbert-base-uncased",
}

# load the files
few_df  = pd.read_csv(FEWSHOT_PATH)
test_df = pd.read_csv(TEST_PATH)

TEXT_COLUMN  = 'text'
LABEL_COLUMN = 'Label'

few_texts   = few_df[TEXT_COLUMN].tolist()
few_labels  = few_df[LABEL_COLUMN].tolist()
test_texts  = test_df[TEXT_COLUMN].tolist()
y_true      = test_df[LABEL_COLUMN].tolist()

print(f"Few-shot : {len(few_df)} samples  (Label 0: {few_labels.count(0)}, Label 1: {few_labels.count(1)})")
print(f"Test     : {len(test_df)} samples  (Label 0: {y_true.count(0)}, Label 1: {y_true.count(1)})")

# function to evaluate
def evaluate(y_true, y_pred, model_name, strategy):
    """Print and return a metrics dict."""
    acc  = accuracy_score(y_true, y_pred)
    f1   = f1_score(y_true, y_pred, average="macro")
    prec = precision_score(y_true, y_pred, average="macro", zero_division=0)
    rec  = recall_score(y_true, y_pred, average="macro", zero_division=0)
    print(f"\n  [{model_name} | {strategy}]")
    print(f"    Accuracy  : {acc:.4f}")
    print(f"    F1 (macro): {f1:.4f}")
    print(f"    Precision : {prec:.4f}")
    print(f"    Recall    : {rec:.4f}")
    print(classification_report(y_true, y_pred,
          target_names=["No Signal (0)", "Burnout/Stress (1)"],
          zero_division=0))
    return {"accuracy": acc, "f1_macro": f1, "precision": prec, "recall": rec}

# step 1 : ZERO SHOT CLASSIFICATION

ZS_CANDIDATE_LABELS = [
   "The author is personally experiencing burnout, stress, or a mental health "
    "struggle related to their cybersecurity job or career.",   #  label 1

    "This is a general cybersecurity discussion with no personal burnout "
    "or mental health signals from the author.",             # label 0
]


def zero_shot(classifier, texts):
    """
    Run HuggingFace zero-shot-classification pipeline.
    The label with the higher score wins , maps to 0 or 1.
    """
    preds = []
    for text in texts:
        result = classifier(text, candidate_labels=ZS_CANDIDATE_LABELS,
                            multi_label=False)
        # index 0 in ZS_CANDIDATE_LABELS → Label 1 (burnout)
        burnout_score  = result["scores"][result["labels"].index(ZS_CANDIDATE_LABELS[0])]
        preds.append(1 if burnout_score >= 0.5 else 0)
    return preds

# STEP 2: ZERO SHOT COT

COT_THEMES = [
    # Theme 1 — Burnout / exhaustion
    (
        "The author is personally experiencing burnout, exhaustion, or feeling overwhelmed by work demands.",
        "The author does not mention burnout or feeling overwhelmed by work."
    ),
    # Theme 2 — Mental health
    (
        "The author personally mentions anxiety, depression, PTSD, or mental health struggles tied to their job.",
        "The author does not mention any mental health struggles related to work."
    ),
    # Theme 3 — Work-life balance
    (
        "The author personally struggles with work-life balance, sleep issues, or feeling emotionally drained.",
        "The author does not mention work-life balance problems or emotional exhaustion."
    ),
    # Theme 4 — Job market stress
    (
        "The author is personally stressed about job searching, interviews, layoffs, or career uncertainty.",
        "The author is not expressing stress about job searching or career uncertainty."
    ),
    # Theme 5 — Toxic workplace
    (
        "The author personally describes a toxic workplace, high pressure environment, or ethical stress at work.",
        "The author does not describe a toxic or high-pressure workplace."
    ),
    # Theme 6 — Self-doubt / imposter syndrome
    (
        "The author personally expresses feeling not good enough, imposter syndrome, or struggling with job tasks.",
        "The author does not express self-doubt or imposter syndrome."
    ),
    # Theme 7 — Motivation / keeping up
    (
        "The author personally struggles to stay motivated or keep up with demands of the cybersecurity field.",
        "The author does not mention difficulty staying motivated in their field."
    ),
]

THEME_THRESHOLD = 0.5   # entailment score needed for a theme to "fire"


def zero_shot_cot(classifier, texts):
    """
    Run each theme as a separate NLI call.
    OR logic: if ANY theme fires (entailment >= threshold) → Label 1.
    This mirrors your labeling: "Matched: ANY keyword" = Label 1.
    """
    preds = []
    for text in texts:
        fired = False
        for pos_label, neg_label in COT_THEMES:
            result = classifier(
                text,
                candidate_labels=[pos_label, neg_label],
                multi_label=False
            )
            pos_score = result["scores"][result["labels"].index(pos_label)]
            if pos_score >= THEME_THRESHOLD:
                fired = True
                break          # one theme is enough — no need to check rest
        preds.append(1 if fired else 0)
    return preds

# EMBEDDING EXTRACTION, FS, FS COT

def mean_pool(token_embeddings, attention_mask):
    """Average token embeddings (ignoring padding)."""
    mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return (token_embeddings * mask_expanded).sum(1) / mask_expanded.sum(1).clamp(min=1e-9)


def get_embeddings(texts, tokenizer, model, batch_size=16):
    """
    Extract [CLS]-pooled or mean-pooled sentence embeddings
    from a base transformer model (no classification head).
    """
    model.eval()
    all_embs = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i: i + batch_size]
        enc = tokenizer(batch, padding=True, truncation=True,
                        max_length=512, return_tensors="pt")
        enc = {k: v.to(device_str) for k, v in enc.items()}
        with torch.no_grad():
            out = model(**enc)
        # Use mean pooling over last hidden state
        embs = mean_pool(out.last_hidden_state, enc["attention_mask"])
        all_embs.append(embs.cpu().numpy())
    return np.vstack(all_embs)

# STEP 3: FEW SHOT (K-NN EMBEDDINGS)


def few_shot(test_texts, few_texts, few_labels,
             tokenizer, model, k=K_NEIGHBORS):
    """
    Encode both sets → cosine similarity → majority vote of k nearest neighbors.
    """
    print("    Encoding few-shot examples ...")
    few_embs  = get_embeddings(few_texts,  tokenizer, model)
    print("    Encoding test samples ...")
    test_embs = get_embeddings(test_texts, tokenizer, model)

    sim_matrix = cosine_similarity(test_embs, few_embs)   # (N_test, N_few)
    preds = []
    for sims in sim_matrix:
        top_k_idx   = np.argsort(sims)[-k:]               # k most similar
        top_k_labels = [few_labels[i] for i in top_k_idx]
        preds.append(int(np.round(np.mean(top_k_labels)))) # majority vote
    return preds

# STEP 4 : FEW SHOT COT
# Each few-shot example is represented as:
#     "<cleaned text> [REASON: <label_reason>]"
#
# This embeds the human reasoning (why a post was labeled 1 or 0)
# directly into the vector space — the k-NN then carries that reasoning.


def few_shot_cot(test_texts, few_texts, few_labels,
                 tokenizer, model, k=K_NEIGHBORS):
    """
    Augment few-shot embeddings with label_reason context.
    The intuition: a test post similar to few-shot posts that have
    specific stress-signal reasons will inherit those signals.
    """
    # Build enriched few-shot text: "post text [REASON: matched keyword list]"
    few_cot_texts = [
        f"{row['test_texs']} [REASON: {row['label_reason']}]"
        for _, row in few_df.iterrows()
    ]
    few_labels = few_df["Label"].tolist()

    print("    Encoding CoT-enriched few-shot examples ...")
    few_embs  = get_embeddings(few_cot_texts, tokenizer, model)
    print("    Encoding test samples ...")
    test_embs = get_embeddings(test_texts,    tokenizer, model)

    sim_matrix = cosine_similarity(test_embs, few_embs)
    preds = []
    for sims in sim_matrix:
        top_k_idx    = np.argsort(sims)[-k:]
        top_k_labels = [few_labels[i] for i in top_k_idx]
        preds.append(int(np.round(np.mean(top_k_labels))))
    return preds

def run_model(model_name, all_results):
    print(f"\n{'='*60}")
    print(f"  MODEL: {model_name}")
    print(f"{'='*60}")

    nli_ckpt  = NLI_MODELS[model_name]
    base_ckpt = BASE_MODELS[model_name]
    y_true     = test_df[LABEL_COLUMN].tolist()
    test_texts = test_df[TEXT_COLUMN].tolist()
    few_texts  = few_df[TEXT_COLUMN].tolist()
    few_labels = few_df[LABEL_COLUMN].tolist()

    results = {}

    # ── A. Zero-Shot ──────────────────────────────────────────────
    print(f"\n  Loading NLI model: {nli_ckpt}")
    try:
        clf = pipeline("zero-shot-classification",
                       model=nli_ckpt, device=DEVICE)

        print("\n  Running Zero-Shot ...")
        preds_zs = zero_shot(clf, test_texts)
        results["ZeroShot"] = evaluate(y_true, preds_zs, model_name, "Zero-Shot")

        # ── B. Zero-Shot CoT ──────────────────────────────────────
        print("\n  Running Zero-Shot CoT ...")
        preds_zscot = zero_shot_cot(clf, test_texts)
        results["ZeroShot_CoT"] = evaluate(y_true, preds_zscot, model_name, "Zero-Shot CoT")

        del clf   # free memory
        torch.cuda.empty_cache() if torch.cuda.is_available() else None

    except Exception as e:
        print(f"   NLI model failed: {e}")
        results["ZeroShot"]     = {"error": str(e)}
        results["ZeroShot_CoT"] = {"error": str(e)}

    # ── C & D. Few-Shot / Few-Shot CoT (use base model embeddings) ──
    print(f"\n  Loading base model: {base_ckpt}")
    try:
        tokenizer = AutoTokenizer.from_pretrained(base_ckpt)
        model     = AutoModel.from_pretrained(base_ckpt).to(device_str)

        print("\n  Running Few-Shot ...")
        preds_fs = few_shot(test_texts, few_texts, few_labels,
                            tokenizer, model)
        results["FewShot"] = evaluate(y_true, preds_fs, model_name, "Few-Shot")

        print("\n  Running Few-Shot CoT ...")
        preds_fscot = few_shot_cot(test_texts, few_texts, few_labels,
                                   tokenizer, model)
        results["FewShot_CoT"] = evaluate(y_true, preds_fscot, model_name, "Few-Shot CoT")

        del model, tokenizer
        torch.cuda.empty_cache() if torch.cuda.is_available() else None

    except Exception as e:
        print(f"  Base model failed: {e}")
        results["FewShot"]     = {"error": str(e)}
        results["FewShot_CoT"] = {"error": str(e)}

    all_results[model_name] = results

# run all models
all_results = {}
for model_name in ["BERT", "RoBERTa", "DistilBERT"]:
    run_model(model_name, all_results)

# save results
with open(RESULTS_PATH, "w") as f:
    json.dump(all_results, f, indent=2)
print(f"\n Results saved to {RESULTS_PATH}")

#summary
rows = []
for model, strategies in all_results.items():
    for strat, metrics in strategies.items():
        if "accuracy" in metrics:
            rows.append({
                "Model":     model,
                "Strategy":  strat,
                "Accuracy":  round(metrics["accuracy"], 4),
                "F1_Macro":  round(metrics["f1_macro"], 4),
                "Precision": round(metrics["precision"], 4),
                "Recall":    round(metrics["recall"], 4)
            })

summary = pd.DataFrame(rows)
# Corrected: Specify a filename for the CSV within the directory
SUMMARY_PATH = "/content/drive/MyDrive/Colab Notebooks/bert/summary_withoutFINETUNE.csv"
pd.set_option("display.float_format", lambda x: "{:.4f}".format(x))
print(summary.to_string(index=False))
summary.to_csv(SUMMARY_PATH, index=False)
print(f"\nSummary saved  {SUMMARY_PATH}")